api_valid_code:
    resource: "@apiValidCodeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
app_auth:
    resource: "@AppBundle/Resources/config/routing/auth.php"
    prefix:   /